// Single source of truth for the GMAX VSL b-roll wiring.
//
// `tools/fetch_pixabay.py` REGENERATES the fenced region below after pulling
// fresh footage from the Pixabay API: it flips BROLL_DIR to "broll-gmax", points
// each beat at its downloaded g*.mp4, records the correct native loop length (in
// frames) for every clip so <Loop> tiles it seamlessly, and — when a matching
// still is fetched — fills BROLL_STILL so a poster frame backs each clip.
//
// The committed defaults use the bundled public/broll/c*.mp4 set, so the project
// always renders even before a fetch. Do NOT hand-edit between the fetch markers.

// Native frame rate of the source clips; loop lengths are seconds * this value.
export const GMAX_BROLL_FPS = 30;

// --- fetch:begin (regenerated by tools/fetch_pixabay.py — do not hand-edit) ---
export const BROLL_DIR = "broll";

// Beat key -> clip filename, in timeline order.
export const BROLL = {
  open: "c2.mp4", //  0  quiet open — owner at desk
  hook: "c3.mp4", //  1  hook — losing your best people
  door: "c4.mp4", //  3  the group plan ends at the door
  cost: "c1.mp4", //  5  the hidden cost of turnover
  portable: "c0.mp4", //  8  a benefit that follows the person
  team: "c3.mp4", // 12  built for teams of 10–60
  cta: "c2.mp4", // 13  CTA over b-roll
} as const;

// Clip filename -> native length in frames, for a seamless <Loop>.
export const BROLL_LOOP: Record<string, number> = {
  "c0.mp4": 409,
  "c1.mp4": 432,
  "c2.mp4": 305,
  "c3.mp4": 222,
  "c4.mp4": 202,
  "c5.mp4": 343,
  "c6.mp4": 320,
};

// Clip filename -> still image (in BROLL_DIR) shown behind the clip as a poster.
// Empty by default; the fetch tool fills it when it also pulls Pixabay photos.
export const BROLL_STILL: Record<string, string> = {};
// --- fetch:end ---

export type BrollBeat = keyof typeof BROLL;
